### ISSUE TITLE
`ERROR:root:Gate Phase(0.5) unsupported by PHIR`

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-phir#136]
**Describe the bug**

Converting a circuit containing some conditional `Phase` operations fails with the following message:

```
ERROR:root:Gate Phase(0.5) unsupported by PHIR
Traceback (most recent call last):
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pytket/phir/phirgen.py", line 172, in convert_subcmd
    gate = tket_gate_to_phir[op.type]
KeyError: <OpType.Phase: 21>
Traceback (most recent call last):
  File "/home/alec/tmp/dan/test.py", line 8, in <module>
    print(pytket_to_phir(circ))
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pytket/phir/api.py", line 70, in pytket_to_phir
    phir_json = genphir(placed, machine_ops=bool(machine))
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pytket/phir/phirgen.py", line 416, in genphir
    append_cmd(shard.primary_command, ops)
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pytket/phir/phirgen.py", line 301, in append_cmd
    op: JsonDict | None = convert_subcmd(cmd.op, cmd)
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pytket/phir/phirgen.py", line 231, in convert_subcmd
    "true_branch": [convert_subcmd(op.op, cmd)],
  File "/home/alec/tmp/env/lib/python3.10/site-packages/pytket/phir/phirgen.py", line 172, in convert_subcmd
    gate = tket_gate_to_phir[op.type]
KeyError: <OpType.Phase: 21>
```

**To Reproduce**

With the JSON file attached:
[circ.json](https://github.com/CQCL/pytket-phir/files/14376159/circ.json)

```python
from pytket import Circuit
import json
from pytket.phir.api import pytket_to_phir

with open("circ.json", "r") as fp:
    circ = Circuit.from_dict(json.load(fp))

print(pytket_to_phir(circ))
```

Reproduced with pytket 1.25.0, pytket-phir 0.4.3.

**Expected behavior**

The circuit should be converted to PHIR.

**Additional context**

I tried to make the example smaller, but this proved strangely difficult. For example, after removing just the _last_ conditional `Phase` operation the conversion succeeded (even though there are others in the circuit). So I'm not sure what's going on.

**Comment by qartik** [comment]
Hey @qciaran, does PECOS/PHIR support Phase, ie, Global phase? We currently don't have it in the spec table at https://github.com/CQCL/phir/blob/main/spec.md#table-ii---quantum-operations

**Comment by qciaran** [comment]
If `Phase` truly is a global phase, since global phases are un-physical I would think we would just skip over them/ignore them. Phases of gates only matter if you are doing some sort of conditional unitary.

**Comment by qciaran** [comment]
Yeah, as per https://tket.quantinuum.com/api-docs/optype.html `Phase` is a global phase. So I would just pass/skip on it unless there is something I am missing.
